### ISSUE TITLE
iOSアプリではアカウント登録なのにドキュメントではユーザー登録になっている

### ISSUE THREAD

**Issue by keigo-brook** [YUKAI/bocco-api-docs#17]
アプリ側
![img_0204 2](https://cloud.githubusercontent.com/assets/7877887/19177422/0c54db66-8c84-11e6-92be-d7519109538f.PNG)

ドキュメント側
http://api-docs.bocco.me/get_access_token.html#section-1

どちらかに統一した方が良いと思いますがどうしましょうか？

**Comment by kiryuxxu** [comment]
@keigo-brook 修正お願いします。
