### ISSUE TITLE
音声ファイル取得の方法をリファレンスに掲載する

### ISSUE THREAD

**Issue by harajune** [YUKAI/bocco-api-docs#24]
音声ファイルの取得方法についてドキュメントに記載されていないため、ダウンロード方法がわからない。

下記の2点を追記する必要がある。
- 音声のダウンロードにはaccess_tokenを付与する必要がある
- URL末尾の拡張子を.wavに変えることでwavファイルの取得が可能

例えば、`https://api.bocco.me/alpha/messages/95c509eb-14bd-4e3d-a8ef-49c05b59aeee.wav`の音声をダウンロードする場合は、URL末尾に`?access_token=xxxxxxxx`のようにaccess_tokenを渡す必要がある。

**Comment by keigo-brook** [comment]
メッセージのaudioについてなんですが, 拡張子が.ogg のときと .m4a のときがあるようです。

これらの場合も拡張子は.wavを使いますか？

**Comment by harajune** [comment]
実は、そのあたりは裏設定が色々あるのですが、下記のような感じでOKです。隠しているというよりは、仕様が変わりやすいところなので混乱しないように出してない感じです。
- 基本的にはメッセージ取得のAPIで返却されたURLを使う
- ただし、wavがほしい場合は.wavに置換するとwavが取得できる

**Comment by harajune** [comment]
PR取り込みましたー。
