### ISSUE TITLE
「メッセージを送信する」では、リクエストHeadersに日本語の指定が必要

### ISSUE THREAD

**Issue by loonaifactory** [YUKAI/bocco-api-docs#36]
Google Apps Scriptを使って、BOCCO API：メッセージの送信をしたところ、
チャットルームには意図した日本語が表示されたのですが、
BOCCOくんが英語を話し始めました。

Headersに"Accept-Language : ja"が必要なのですね。
チュートリアルには記載されていたのですが、
リファレンスには記載がないようです。

**Comment by harajune** [comment]
ありがとうございます！追記対応したいと思います。
