### ISSUE TITLE
チュートリアル「チャットルームを取得する」の説明に関する誤り

### ISSUE THREAD

**Issue by kotobuki** [YUKAI/bocco-api-docs#37]
以下のページの説明の中で

http://api-docs.bocco.me/get_joined_rooms.html#section-2

以下の例に関する説明において「curl を使った場合のリクエスト例」として`apikey`が必要であると説明されているのですが、実際には`access_token`ではないかと思います。

```sh
curl -i "https://api.bocco.me/alpha/rooms/joined?access_token=x2c4sjxacw4tq72q5h9vrsgjbcz3p55ixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
```

もし勘違いでしたらすみません。

**Comment by harajune** [comment]
ご指摘ありがとうございます！ご指摘の通りと思いますので修正いたします。
